[package]
name = "lombok"
version = "0.1.0"
description = "Lombok port for Rust"
authors = ["sokomishalov <sokomishalov@mail.ru>"]
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
lombok-trait = { path = "lombok-trait" }
lombok-derive = { path = "lombok-derive" }