[package]
name = "lombok-derive"
version = "0.1.0"
authors = ["sokomishalov <sokomishalov@mail.ru>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"